apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: ns-registry
type: Opaque
stringData:
  # Install apache2-utils
  # Check installation: which htpasswd
  # New password command: htpasswd -nb registry <newPass>
  auth: "registry:<insertYourPass>"
