apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: ns-registry
type: Opaque
data:
  # Format HAProxy Basic Auth
  # name: encrypted or base64 encoded string.
  # crypt(3) support multiple encryption algorithm.
  # openssl passwd -5 <yourSecret> | base64 -w 0 (w for disable text wrapping)
  hantu: JDUkVU4xSFBPT1RaS2NCUmRpaCQvc2ppSzIvNE13WkxST3NqN2xFdFhXYmVxVXZ0b0V5WHBmcEZtQmNTb0pCCg==
