# There are multiple ways to implement HAProxy configuration:
# Global: ConfigMap
# Ingress Resource: Ingress Annotations.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: ns-registry
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Get client Real IP address.
    haproxy.org/forwarded-for: "true"
    # https://www.haproxy.com/documentation/kubernetes-ingress/enterprise/configuration-reference/ingress/#auth-secret
    haproxy.org/auth-type: basic-auth
    # Pattern: namespace/secretName. Refer to auth.yaml
    haproxy.org/auth-secret: ns-registry/registry-auth
    # Basic Auth label.
    haproxy.org/auth-realm: "Registry Authentication"
spec:
  ingressClassName: prod
  tls:
    - hosts:
        - registry.hendrywilliam.com
      secretName: letsencrypt-prod
  rules:
    - host: registry.hendrywilliam.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-svc
                port:
                  number: 5000
