apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prdo
spec:
  acme:
    email: hendriwilliam29@gmail.com
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - hendrywilliam.com
            - "*.hendrywilliam.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: api-token
