apiVersion: apps/v1
kind: Deployment
metadata:
  name: moltis
  namespace: ns-moltis
  labels:
    app: moltis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moltis
  template:
    metadata:
      labels:
        app: moltis
    spec:
      containers:
        - name: ubuntu-moltis
          image: ghcr.io/moltis-org/moltis:latest
          ports:
            - name: port-13131
              containerPort: 13131
              protocol: TCP
            - name: port-13132
              containerPort: 13132
              protocol: TCP
          volumeMounts:
            - name: moltis-config
              mountPath: /home/moltis/.config/moltis
            - name: moltis-data
              mountPath: /home/moltis/.moltis
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: moltis-config
          persistentVolumeClaim:
            claimName: moltis-config
        - name: moltis-data
          persistentVolumeClaim:
            claimName: moltis-data
---
apiVersion: v1
kind: Service
metadata:
  name: moltis-svc
  namespace: ns-moltis
  labels:
    app: moltis
spec:
  type: ClusterIP
  selector:
    app: moltis
  ports:
    - name: port-13131
      protocol: TCP
      port: 13131
      targetPort: 13131
    - name: port-13132
      protocol: TCP
      port: 13132
      targetPort: 13132
