apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-config
  namespace: ns-moltis
  labels:
    app: moltis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-data
  namespace: ns-moltis
  labels:
    app: moltis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi
