# Created from User Profile -> API Tokens -> API Tokens
# Permission:
# 1. Zone - DNS - Edit
# 2. Zone - Zone - Read
# Zone Resources:
# Include - All Zones.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  # Must be in the same namespace with certmanager pods.
  namespace: cert-manager
type: Opaque
# Do not encode to base64.
stringData:
  api-token: <API-Token>
