apiVersion: v1
kind: Namespace
metadata:
  name: cert-test-namespace
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-test-namespace
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signedcert
  namespace: cert-test-namespace
spec:
  dnsNames:
    - domain.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
